---
title: "Queer Cult"
author: "Brian Gural"
date: "2023-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r load libs, include=F}
libs <- c("tidyverse", "patchwork", "lubridate", "RColorBrewer", "pals", "ggridges", "viridis", "ggrepel")
lapply(libs, require, character.only = T)
rm(libs)
```

```{r load}
data <- read.csv("data/merged_datasets/many_individuals/queer_cult.csv")
```


```{r plot cumulative time, fig.width=14, fig.height= 8}
# Prepare the data
data <- data %>% 
  mutate(endTime = as.POSIXct(endTime, format="%Y-%m-%d %H:%M")) %>%
  arrange(individual, endTime) %>%
  group_by(individual) %>%
  mutate(start_time = min(endTime),
         days_from_start = as.numeric(difftime(endTime, start_time, units = "days")),
         cumulative_time = cumsum(as.numeric(msPlayed)) / (1000 * 60 * 60 * 24),
         unique_artists = cumsum(!duplicated(artistName)),
         name = case_when(
          str_detect(individual, "ammi") ~ "Ammi",
          str_detect(individual, "gural")  ~ "Brian",
          str_detect(individual, "lester") ~ "Sarah",
          str_detect(individual, "arias") ~ "Gaby",
          str_detect(individual, "hernandez") ~ "Lindsey",
          str_detect(individual, "sharp") ~ "Rachel"))  # convert ms to minutes


data <- data |> 
         group_by(individual) |> 
         arrange(desc(endTime)) |> 
         slice_head(n = 1) |> 
         mutate(label = name) |> 
         right_join(data)




pal <- brewer.pal(length(unique(data$name)), "Dark2")
names(pal) <- unique(data$name)


# Plot by date
label_position <- max(data$endTime) + ((max(data$endTime) - min(data$endTime))/5)


# Create the plot
p.cum.date <- ggplot(data, aes(x = endTime, y = cumulative_time, color = name)) +
  geom_line(size = 2, alpha = 0.7)  +
  labs(title = "Total listening time",
       subtitle = "Running sum of time spent\nlistening to Spotify, by individual",
       x = "Date",
       y = "Cumulative Listening Time (days)") +
  theme_minimal() +
  scale_color_manual(values = pal)  +
  theme(text = element_text(size = 15),
        axis.title = element_text(size = 18),
        title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(1,3,0,0), "cm")) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label), 
                            family = "Spline Sans Mono",
                            xlim = c(label_position, label_position),
                            hjust = "right",
                            # style segment
                            segment.curvature = .001,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            force_pull = 0.4,
                            force = 2,
                            size = 6,
                            fill = "white") 


# plot unique artists 

# Create the plot
p.uni.art <- ggplot(data, aes(x = endTime, y = unique_artists, color = name)) +
  geom_line(size = 2, alpha = 0.7)  +
  labs(title = "Total artists played",
       subtitle = "Running tally of how many unique artists\nan individual has played over the year",
       x = "Date",
       y = "Number of artists") +
  theme_minimal() +
  scale_color_manual(values = pal)  +
  theme(text = element_text(size = 15),
        axis.title = element_text(size = 18),
        title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(1,3,0,0), "cm"),
        plot.subtitle = element_text(size = 16)) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label), 
                            family = "Spline Sans Mono",
                            xlim = c(label_position, label_position),
                            hjust = "right",
                            # style segment
                            segment.curvature = .001,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            force_pull = 0.4,
                            force = 2,
                            size = 6,
                            fill = "white") 

wrap_plots(p.cum.date, p.uni.art, ncol = 2) + plot_annotation(title = "Cumulative Listening Trends",
                                                                theme = theme(plot.title = element_text(size = 25, hjust = 0.5)))

```


```{r artist markers}

library(dplyr)
library(tidyr)

# Calculate the total and variance of listening time per artist per individual
artist_stats <- data %>%
  group_by(name, artistName) %>%
  summarise(
    total_time = sum(msPlayed),
    var_time = var(msPlayed)
  ) %>%
  replace_na(list(var_time = 0))  # Replace NA with 0

# Calculate the between-individual variance for each artist
between_var <- artist_stats %>%
  group_by(artistName) %>%
  summarise(between_var = var(total_time)) %>%
  replace_na(list(between_var = 0))

# Join the within-individual and between-individual stats
artist_stats <- left_join(artist_stats, between_var, by = "artistName")


# Step 1: Identify the top 50 artists for each individual
top_50_artists <- artist_stats %>%
  group_by(name) %>%
  arrange(desc(total_time)) %>%
  slice_head(n = 50) %>%
  ungroup()

# Step 2: Identify artists that are unique to an individual's top 50 list
unique_artists <- top_50_artists %>%
  count(artistName) %>%
  filter(n == 1) %>%
  select(artistName)

# Step 3: Filter the top 50 artists by the unique artists list
unique_top_50_artists <- top_50_artists %>%
  semi_join(unique_artists, by = "artistName")

# Step 4: Arrange by between-individual variance (if needed)
unique_top_50_artists <- unique_top_50_artists %>%
  group_by(name) |> 
  arrange(desc(between_var)) |> 
  slice_head(n = 50) |> 
  arrange(desc(total_time)) |> 
  slice_head(n = 15) |> 
  select(name, artistName)

markers <- unique_top_50_artists %>%
  group_by(name) %>%
  mutate(marker_rank = row_number()) %>%
  ungroup() %>%
  filter(marker_rank <= 15) %>%  # Selecting top 10 unique markers for each individual
  select(name, marker_rank, artistName) %>%
  pivot_wider(names_from = name, values_from = artistName) %>%
  arrange(marker_rank)


colnames(markers)[1] <- c("Marker Rank")

write.csv(markers, "results/queer_cult/markers.csv", row.names = F)
```

```{r marker seasonal}

# Define Seasons
data$season <- case_when(
  lubridate::month(data$endTime) %in% c(3, 4, 5)  ~ 'Spring',
  lubridate::month(data$endTime) %in% c(6, 7, 8)  ~ 'Summer',
  lubridate::month(data$endTime) %in% c(9, 10, 11) ~ 'Autumn',
  lubridate::month(data$endTime) %in% c(12, 1, 2) ~ 'Winter',
  TRUE ~ 'Unknown'
)

# Calculate total and variance of listening time per track per individual for each season
track_stats_seasonal <- data %>%
  group_by(name, season, artistName) %>%
  summarise(
    total_time = sum(msPlayed),
    var_time = var(msPlayed)
  ) %>%
  replace_na(list(var_time = 0))

# Calculate the between-individual variance for each track in each season
between_var_seasonal <- track_stats_seasonal %>%
  group_by(season, artistName) %>%
  summarise(between_var = var(total_time)) %>%
  replace_na(list(between_var = 0))

# Join the within-individual and between-individual stats
track_stats_seasonal <- left_join(track_stats_seasonal, between_var_seasonal, by = c("season", "artistName"))

# Identify the top 50 tracks for each individual for each season
top_50_tracks_seasonal <- track_stats_seasonal %>%
  group_by(name, season) %>%
  arrange(desc(total_time)) %>%
  slice_head(n = 50) %>%
  ungroup()

# Identify tracks that are unique to an individual's top 50 list for each season
unique_tracks <- top_50_tracks_seasonal %>%
  count(season, artistName) %>%
  filter(n == 1) %>%
  select(season, artistName)

# Filter the top 50 tracks by the unique tracks list
unique_top_50_tracks_seasonal <- top_50_tracks_seasonal %>%
  semi_join(unique_tracks, by = c("season", "artistName"))


# Step 4: Arrange by between-individual variance (if needed)
top_seasonal <- unique_top_50_tracks_seasonal %>%
  group_by(name, season) |> 
  arrange(desc(between_var)) |> 
  slice_head(n = 25) |> 
  arrange(desc(total_time)) |> 
  slice_head(n = 3) 



# Arrange by between-individual variance and then by total time
unique_top_50_tracks_seasonal <- unique_top_50_tracks_seasonal %>%
  arrange(desc(between_var), desc(total_time))
```

```{r plot markers seasonal, fig.width=14, fig.height= 14}

# Create a plot
ggplot(top_seasonal, aes(x = artistName, y = total_time, fill = name)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = artistName), angle = 90, hjust = 0.1) +
  facet_wrap(season~name, scales = "free_x", drop = TRUE, nrow = 4)  +
  labs(title = "Seasonal Marker Songs by Individual",
       x = "Artist Name",
       y = "Total Time Played") +
  scale_fill_manual(values = pal)  +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank()
  )

```

