---
title: "Time of day analysis"
author: "Brian Gural"
date: "2023-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libs, results = 'hide', include=F}
#devtools::install_github("nsgrantham/ggdark")
libs <- c("tidyverse", "gplots", "viridis", "factoextra", "shiny", "DT", "magrittr", "dplyr",
          "ggdark", "pals")
lapply(libs, require, character.only = T)
```

```{r load data, include=F}
#lis.df <- read.csv("data/list_attr/bg_1y_t100.csv") # for non-shiny paths
lis.df <- read.csv("data/merged_datasets/bg_1y_t500.csv")
def.attr <- read.csv("data/attributes/attribute_definitions.csv")
temp.df <- read.csv("data/raw/individuals/bgural/listen_history_1year.csv", row.names = 1)
```

```{r format times}

# Convert endTime to POSIXct
temp.df$endTime <- as.POSIXct(temp.df$endTime, format="%Y-%m-%d %H:%M")
  

# Merge temp.df and lis.df based on trackName and artistName
merged.df <- inner_join(temp.df, lis.df, by = c("trackName" = "track_name", "artistName" = "artist_name"))

# Calculate metrics
final.df <- temp.df %>%
  mutate(
    day_of_week = weekdays(endTime),
    weekday_or_weekend = case_when(
      day_of_week %in% c("Saturday", "Sunday") ~ "Weekend",
      TRUE ~ "Weekday"
    ),
    period_of_day = case_when(
      hour(endTime) >= 6 & hour(endTime) < 12 ~ "Morning",
      hour(endTime) >= 12 & hour(endTime) < 18 ~ "Afternoon",
      hour(endTime) >= 18 & hour(endTime) < 24 ~ "Evening",
      TRUE ~ "Night"
    )
  )


```


```{r plot heatmap, fig.width=20, fig.height=6}
# Assuming final.df has a 'date' column in YYYY-MM-DD format
final.df <- final.df %>%
  mutate(endTime = ymd_hms(endTime, tz = "UTC") %>% with_tz("America/New_York"))

final.df <- final.df %>%
  mutate(year = year(endTime),
         month = month(endTime, label=TRUE),
         day = day(endTime),
         hour = hour(endTime)
         )

# Create a summary data frame to plot
plot_df <- final.df %>%
  group_by(year, month, day, hour, period_of_day) %>%
  summarise(min_listened = sum(msPlayed)/(60*1000)) %>%
  ungroup()

p <- ggplot(plot_df, aes(x = day, y = hour, fill = min_listened)) +
  geom_tile(size = 0.1) +
  scale_fill_viridis(name = "Minutes Played", option = "C") +
  facet_wrap(year ~ month, nrow = 1, labeller = label_wrap_gen(multi_line=FALSE)) +
  scale_y_continuous(trans = "reverse", breaks = c(0, 6, 12, 18,24)) +
  scale_x_continuous(breaks = c(15,30)) +
  theme_minimal(base_size = 8) +
  labs(title = "Minutes played, hour-by-hour, over the past year", x = "Day (split into months)", y = "Time of day (binned into hour blocks)") +
  theme(legend.position = "bottom",
        panel.spacing = unit(0, "lines"),
        plot.title = element_text(size = 14),
        axis.text.y = element_text(size = 6),
        strip.background = element_rect(colour = "white"),
        axis.ticks = element_blank(),
        axis.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6),
        panel.grid.minor = element_blank(),
        axis.ticks.x = element_blank())


p + dark_theme_gray(base_family = "Fira Sans Condensed Light", base_size = 14) + 
  theme(plot.title = element_text(family = "Fira Sans Condensed"),
        plot.background = element_rect(fill = "grey10"),
        panel.background = element_blank(),
        panel.grid.major = element_line(color = "grey30", size = 0.2),
        panel.grid.minor = element_line(color = "grey30", size = 0.2),
        panel.spacing = unit(0, "lines"),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        legend.key = element_blank(),
        legend.position="bottom")

```

```{r day of week over time prep}

day.df <- temp.df %>%
  mutate(endTime = ymd_hms(endTime, tz = "UTC") %>% with_tz("America/New_York"))
day.df$time_of_day <- lubridate::hour(day.df$endTime) + lubridate::minute(day.df$endTime) / 60
day.df$day_of_week <- weekdays(day.df$endTime)


day.df$day_of_week <- factor(day.df$day_of_week, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))


```

```{r day of week plot, fig.width=7, fig.height=10}

ggplot(day.df, aes(x = time_of_day, fill = day_of_week)) +
  geom_density(alpha = 0.5) +
  scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(breaks = c(0,6,12,18,24),
                     limits = c(0,24)) +
  scale_y_continuous(breaks = c(0,0.05,0.1,0.15),
                     limits = c(0,0.15)) +
  facet_wrap(~ day_of_week, scales = "free", ncol = 1,
             strip.position = "right") +
  labs(title = "Density of Listening Time Across Different Days of the Week",
       x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(
    strip.background = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )


```


```{r top days , fig.width=20, fig.height=15}

library(lubridate)
library(lubridate)
library(dplyr)
library(ggplot2)

# Add a date_only column and an hour column to final.df
final.df <- final.df %>% mutate(
  date_only = as.Date(endTime),
  hour = lubridate::hour(endTime)
)

# Identify the top 5 days based on total listening time
top_5_days <- final.df %>% 
  group_by(date_only) %>% 
  summarise(total_time = sum(msPlayed)) %>% 
  arrange(desc(total_time)) %>% 
  slice_head(n = 5) %>% 
  pull(date_only)

# Identify the top 10 artists for each of the top 5 days
top_10_by_day <- final.df %>% 
  filter(date_only %in% top_5_days) %>%
  group_by(date_only, artistName) %>% 
  summarise(total_time_minutes = sum(msPlayed) / (1000 * 60), .groups = 'drop') %>% 
  arrange(date_only, desc(total_time_minutes)) %>% 
  group_by(date_only) %>% 
  slice_head(n = 10) %>% 
  summarise(artist_list = list(unique(artistName)))

# Generate total listening time by hour for the top 5 days
total_time_by_hour <- final.df %>% 
  filter(date_only %in% top_5_days) %>% 
  group_by(date_only, hour) %>% 
  summarise(total_time_minutes = sum(msPlayed) / (1000 * 60), .groups = 'drop')

# Generate total listening time by artist and hour for the top 5 days
top_10_time_by_hour <- final.df %>% 
  group_by(date_only, hour, artistName) %>% 
  summarise(total_time_minutes = sum(msPlayed) / (1000 * 60), .groups = 'drop') 

# Generate the plots using mapply
plot_list <- mapply(function(date, artists) {
  ggplot(aes(x=Sub, y=Prop, fill=CellType))  +
   geom_bar(stat='identity',
           position = "fill",
           width = 0.8,
           color = "black")
  
  
  ggplot() +
    geom_bar(data = total_time_by_hour %>% filter(date_only == date),
             aes(x = hour, y = total_time_minutes),
             stat = "identity", fill = "grey70") +
    geom_bar(data = top_10_time_by_hour %>% filter(date_only == date, artistName %in% artists),
             aes(x = hour, y = total_time_minutes, fill = artistName),
             stat = "identity", color = "black") +
    scale_fill_manual(values = as.vector(pals::kelly(17))) +
    labs(title = paste0("Listening Time for ", date),
         x = "Hour of the Day",
         y = "Total Listening Time (minutes)") +
    theme_minimal()
}, top_5_days, top_10_by_day$artist_list, SIMPLIFY = FALSE)

# Combine the individual plots into a grid
patchwork::wrap_plots(plot_list, ncol = 2)

```


```{r working top  days plots, fig.width=20, fig.height=15}

# Add a date_only column and an hour column to final.df
final.df <- final.df %>% mutate(
  date_only = as.Date(endTime),
  hour = lubridate::hour(endTime)
)
top_5_days <- final.df %>% 
  group_by(date_only) %>% 
  summarise(total_time = sum(msPlayed)) %>% 
  arrange(desc(total_time)) %>% 
  slice_head(n = 5) %>% 
  pull(date_only)

top_10_artists_each_day <- final.df %>%
  filter(date_only %in% top_5_days) %>%
  group_by(date_only, artistName) %>%
  summarise(total_time = sum(msPlayed)) %>%
  arrange(date_only, desc(total_time)) %>%
  group_by(date_only) %>%
  slice_head(n = 10) %>%
  ungroup()

top_10_artists <- unique(top_10_artists_each_day$artistName)


total_time_by_hour <- final.df %>% 
  filter(date_only %in% top_5_days) %>% 
  group_by(date_only, hour) %>% 
  summarise(total_time_minutes = sum(msPlayed) / (1000 * 60))


top_10_time_by_hour <- final.df %>% 
  filter(date_only %in% top_5_days, artistName %in% top_10_artists) %>% 
  group_by(date_only, hour, artistName) %>% 
  summarise(total_time_minutes = sum(msPlayed) / (1000 * 60))


plot_list <- lapply(top_5_days, function(date) {
  ggplot() +
    geom_bar(data = total_time_by_hour %>% filter(date_only == date),
             aes(x = hour, y = total_time_minutes),
             stat = "identity", fill = "grey70") +
    geom_bar(data = top_10_time_by_hour %>% filter(date_only == date),
             aes(x = hour, y = total_time_minutes, fill = artistName),
             stat = "identity", color = "black") +
    scale_fill_manual(values = as.vector(pals::polychrome(29))) +
    labs(title = paste0("Listening Time for ", date),
         x = "Hour of the Day",
         y = "Total Listening Time (minutes)") +
    theme_minimal()
})


# Combine the individual plots into a grid
patchwork::wrap_plots(plot_list, ncol = 2)



```