---
title: "Extended History Exploration"
author: "Brian Gural"
date: "2023-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load libs}
libs <- c("tidyverse", "patchwork", "lubridate", "RColorBrewer", "pals", "ggridges", "viridis")
lapply(libs, require, character.only = T)
rm(libs)
```

```{r load data}
name <- "Brian"
id <- 'bgural'
df <- read.csv(paste0("~/data/raw/individuals/", id, "/extended/MyData/listen_history_a.csv"), row.names = 1)

```
```{r data cleaning}

df <- df %>%
  mutate(endTime = lubridate::ymd_hms(ts),
         endTime = lubridate::with_tz(endTime, tzone = "America/New_York"),
         minute  = lubridate::minute(endTime),
         hour    = lubridate::hour(endTime),
         month   = lubridate::month(endTime, label = T),
         year    = lubridate::year(endTime),
         hoursPlayed = ms_played / 3600000,
         artistName = master_metadata_album_artist_name,
         trackName = master_metadata_track_name,
         msPlayed = ms_played) %>% 
  subset(!is.na(artistName))

df <- df |> 
      select(trackName, artistName, msPlayed, reason_start, reason_end, shuffle, skipped, platform)

write.csv(df, paste0("~/data/raw/individuals/", id, "/extended/MyData/cleaned_hist.csv"), row.names = F)
```

```{r plot intro graphs, fig.width= 6, fig.height=6}
top.artists <- df %>%
  group_by(artistName) %>%
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) %>%
  arrange(desc(hr_played))%>%
  head(10) |> 
  pull(artistName)

pal <- pals::kelly(10)
names(pal) <- top.artists

total.artist <- df %>%
  group_by(artistName) %>%
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) %>%
  arrange(desc(hr_played))%>%
  head(10) 

# make custom palette 

df$trackName_wrap = str_wrap(df$trackName, width = 20)


#Turn your 'treatment' column into an ordered factor 
total.artist$artistName <-  factor(total.artist$artistName, levels=top.artists)


# Get listening time by artist
p.total.artist <- total.artist |> 
  ggplot(aes(x = artistName, y = hr_played, fill = artistName)) +
  geom_col(colour="black") +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_x_discrete(limits = rev(levels(total.artist$artistName))) + 
  xlab("Artist") +
  ylab("Total Hours Listened") +
  ggtitle("Total Listening Time Per Artist") +
  theme_minimal() +
  theme(
    legend.position = "none"
  )

# Summarize listening trends of artists by time of day
daily.artists <- df |> 
  subset(artistName == top.artists) |> 
  mutate(time_of_day = as.numeric(hour) + as.numeric(minute/60)) 
  #Turn your 'treatment' column into an ordered factor 
daily.artists$artistName <-  factor(daily.artists$artistName, levels=top.artists)

p.daily.artists <- daily.artists |> 
  ggplot(aes(x = time_of_day, y = artistName, group = artistName)) +
    geom_density_ridges_gradient(aes(fill = artistName), alpha = 0.5, scale = 1.2, color = "black") + 
    scale_fill_manual(values=as.vector(kelly(10))) +
    scale_x_continuous(breaks = c(0,6,12,18,24),
                     limits = c(0,24)) +
    scale_y_discrete(limits = rev(levels(daily.artists$artistName))) + 
    labs(title = "Daily listening times of top artists",
         x = "Daily listening density") +
    theme_minimal() +
    theme(
      strip.background = element_blank(),
      axis.ticks = element_blank(),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
  )



yearly.artists <-  df |> 
  subset(artistName %in% top.artists) |> 
  mutate(date_only = as.Date(endTime))

#Turn 'treatment' column into an ordered factor 
yearly.artists$artistName <-  factor(yearly.artists$artistName, levels=top.artists)


p.yearly.artists <- yearly.artists |> 
  ggplot(aes(x = date_only, y = artistName, group = artistName)) +
    geom_density_ridges(aes(fill = artistName), 
                        inherit.aes = T,
                        scale = 1.2,
                        color = "black") +
    scale_fill_manual(values=as.vector(kelly(10))) +
    scale_y_discrete(limits = rev(levels(yearly.artists$artistName))) +
    labs(title = "When artists were played overall",
         x = "Date") +
    theme_minimal() +
    theme(
      strip.background = element_blank(),
      axis.ticks = element_blank(),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
  )


```

```{r plot intro graphs, fig.width= 14, fig.height=8}
design <- "DGG" 
w.artist <- wrap_plots( 
           D = p.total.artist, #E = p.daily.artists, 
           G = p.yearly.artists, design = design)

#png_path_1 <- "~/results/readme/images/brian_tartists_09242023.png"
#if(file.exists(pdf_path_1) == F) {
#png(png_path_1, width = 14, height = 8, units = "in", res = 300)}
w.artist + plot_annotation(title = paste0(name, "'s Top Artists"),
                           theme = theme(plot.title = element_text(size = 25)))

#dev.off()
```
```{r basic visuals, echo=FALSE}


# Plot listening habits by time of day
p.time.hourly <- df %>%
  count(hour) %>%
  ggplot(aes(x = hour, y = n, fill = n)) +
  geom_col(colour="black") +
  scale_fill_viridis() +
  xlab("Hour of Day") +
  ylab("Frequency") +
  ggtitle("Tracks Started by Time of Day") +
  theme_minimal() +
  theme(
    legend.position = "none"
  )

# make custom palette 

df$trackName_wrap = str_wrap(df$trackName, width = 20)


# Plot top tracks     
p.top.tracks <- df |>
  group_by(trackName_wrap, artistName) |> 
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) |> 
  ungroup() |> 
  slice_max(n = 20, order_by = hr_played) %>%
  ggplot(aes(x = reorder(trackName_wrap, hr_played), y = hr_played, fill = artistName)) +
  geom_col(colour="black") +
  coord_flip() +
  scale_fill_manual(values=as.vector(kelly(22)))  +
  ylab("Hours listened") +
  ggtitle("Top 20 Most Listened Tracks") +
  labs(colour="Artist") +
  theme_minimal() + 
  theme(
    legend.position = c(0.7, 0.4),
    legend.background = element_rect(fill="white",
                                  size=0.5, linetype="solid", 
                                  colour ="black"),
    axis.title.y = element_blank()
  )

# Plot monthly listening time
p.time.monthly <- df %>%
  group_by(month) %>%
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) %>%
  ggplot(aes(x = month, y = hr_played, fill = hr_played)) +
  geom_col(colour="black")  +
  scale_fill_viridis() +
  xlab("Month") +
  ylab("Hours Listened") +
  ggtitle("Cumulative Listening by Month") +
  theme_minimal() +
  theme(
    legend.position = "none"
  )



```

```{r plot intro graphs, fig.width= 14, fig.height=8}
design <- "CB
           CA" 
w.person <- wrap_plots(A = p.time.monthly,  B = p.time.hourly, 
           C = p.top.tracks,     
           E = p.daily.artists, G = p.yearly.artists, design = design)

#png_path_2 <- "~/results/readme/images/brian_summary_09242023.png"
#if(file.exists(pdf_path_2) == F) {
#png(png_path_2, width = 14, height = 8, units = "in", res = 300)}


w.person + plot_annotation(title = paste0(name, "'s favorite music and listening times"),
                           theme = theme(plot.title = element_text(size = 25)))

#dev.off()
```

```{r plot intro graphs, fig.width= 14, fig.height=8}
library(tidyverse)
library(lubridate)
library(ggridges)



####!!!!!!!
# make a plot that is like the wrapped artist plots, but has a column of a plot that is the top ip.addresses

####

# Assuming 'df' is your data frame
# Assuming your column names match the one in the example

# Calculate the total listening time per IP address

top.ip <- df %>%
  group_by(ip_addr_decrypted) %>%
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) %>%
  arrange(desc(hr_played))%>%
  head(10) |> 
  pull(ip_addr_decrypted)

pal <- pals::kelly(10)
names(pal) <- top.ip

total.ip <- df %>%
  group_by(ip_addr_decrypted) %>%
  summarise(hr_played = sum(as.numeric(msPlayed)/(1000*60*60))) %>%
  arrange(desc(hr_played))%>%
  head(10)


#Turn your 'treatment' column into an ordered factor 
total.ip$ip_addr_decrypted <-  factor(total.ip$ip_addr_decrypted, levels=top.ip)


# Get listening time by artist
p.total.artist <- total.ip |> 
  ggplot(aes(x = ip_addr_decrypted, y = hr_played, fill = ip_addr_decrypted)) +
  geom_col(colour="black") +
  coord_flip() +
  scale_fill_manual(values = pal) +
  scale_x_discrete(limits = rev(levels(total.ip$ip_addr_decrypted))) + 
  xlab("IP Address") +
  ylab("Total Hours Listened") +
  ggtitle("Total Listening Time Per IP Address") +
  theme_minimal() +
  theme(
    legend.position = "none"
  )

# Summarize listening trends of artists by time of day
daily.artists <- df |> 
  subset(ip_addr_decrypted %in% top.ip) |> 
  mutate(time_of_day = as.numeric(hour) + as.numeric(minute/60)) 
  #Turn your 'treatment' column into an ordered factor 
daily.artists$ip_addr_decrypted <-  factor(daily.artists$ip_addr_decrypted, levels=top.ip)

p.daily.artists <- daily.artists |> 
  ggplot(aes(x = time_of_day, y = ip_addr_decrypted, group = ip_addr_decrypted)) +
    geom_density_ridges_gradient(aes(fill = ip_addr_decrypted), alpha = 0.5, scale = 1.2, color = "black") + 
    scale_fill_manual(values=as.vector(kelly(10))) +
    scale_x_continuous(breaks = c(0,6,12,18,24),
                     limits = c(0,24)) +
    scale_y_discrete(limits = rev(levels(daily.artists$ip_addr_decrypted))) + 
    labs(title = "Daily listening times of IP Addresses",
         x = "Daily listening density") +
    theme_minimal() +
    theme(
      strip.background = element_blank(),
      axis.ticks = element_blank(),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
  )



yearly.artists <-  df |> 
  subset(ip_addr_decrypted %in% top.ip) |> 
  mutate(date_only = as.Date(endTime))

#Turn 'treatment' column into an ordered factor 
yearly.artists$ip_addr_decrypted <-  factor(yearly.artists$ip_addr_decrypted, levels=top.ip)


p.yearly.artists <- yearly.artists |> 
  ggplot(aes(x = date_only, y = ip_addr_decrypted, group = ip_addr_decrypted)) +
    geom_density_ridges(aes(fill = ip_addr_decrypted), 
                        inherit.aes = T,
                        scale = 1.2,
                        color = "black") +
    scale_fill_manual(values=as.vector(kelly(10))) +
    scale_y_discrete(limits = rev(levels(yearly.artists$ip_addr_decrypted))) +
    labs(title = "When IP Addresses were used",
         x = "Past year listening density") +
    theme_minimal() +
    theme(
      strip.background = element_blank(),
      axis.ticks = element_blank(),
      legend.position = "none",
      panel.grid.minor = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank()
  )



```

```{r plot intro graphs, fig.width= 14, fig.height=8}
design <- "DGG" 
w.artist <- wrap_plots( 
           D = p.total.artist, #E = p.daily.artists, 
           G = p.yearly.artists, design = design)

#png_path_1 <- "~/results/readme/images/brian_tartists_09242023.png"
#if(file.exists(pdf_path_1) == F) {
#png(png_path_1, width = 14, height = 8, units = "in", res = 300)}
w.artist + plot_annotation(title = paste0(name, "Top Artists"),
                           theme = theme(plot.title = element_text(size = 25)))

#dev.off()
```

```{r geolocataion}
#devtools::install_github("ironholds/rgeolocate")
#install.packages("locateip")
library("locateip")

#ip.locations <- sapply(top.ip, function(x){
#              locate_ip(ip=x, fields=c("status,message,country,regionName,city,lat,lon"), 
#                        lang="en", tidy=TRUE ) })
```
