---
title: "Untitled"
author: "Brian Gural"
date: "2023-11-14"
output: html_document
---
---
title: "Year-by-year comparison"
author: "Brian Gural"
date: "2023-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r load libs, include=F}
libs <- c("tidyverse", "patchwork", "lubridate", "RColorBrewer", "pals", "ggridges", "viridis", "ggrepel")
lapply(libs, require, character.only = T)
rm(libs)
```

```{r load data}
# Load data
id <- 'Sarah_Lester'
name <- str_split(id, "_")[[1]][1]
df <- read.csv(paste0("/home/rstudio/data_private/raw/individuals/", id, "/extended_clean.csv"))

```

```{r plot cumulative time, fig.width=14, fig.height= 8}
# Prepare the data
df <- df %>% 
  mutate(endTime = as.POSIXct(endTime, format="%Y-%m-%d %H:%M"),
         day_of_year = yday(endTime)) %>% 
  arrange(year, endTime) %>%
  group_by(year) %>%
  mutate(cumulative_time = cumsum(as.numeric(msPlayed)) / (1000 * 60 * 60 * 24),
         unique_artists = cumsum(!duplicated(artistName)),
         cumulative_plays = cumsum(as.numeric(percent_listened)))  # convert ms to minutes


df <- df |> 
         group_by(year) |> 
         arrange(desc(endTime)) |> 
         slice_head(n = 1) |> 
         mutate(label = year) |> 
         right_join(df)




pal <- brewer.pal(length(unique(df$year)), "Set3")
names(pal) <- unique(df$year)


# Create the plot
p.cum.time <- ggplot(df, aes(x = day_of_year, y = cumulative_time, color = as.factor(year))) +
  geom_line(size = 2)  +
  labs(title = "Total listening time",
       subtitle = "Running sum of time spent listening to Spotify, by year",
       x = "Day in year",
       y = "Cumulative Listening Time (days)") +
  theme_minimal() +
  scale_color_manual(values=as.vector(watlington(length(unique(df$year))))) +
  theme(text = element_text(size = 15),
        axis.title = element_text(size = 18),
        title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(1,3,0,0), "cm")) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label), 
                            family = "Spline Sans Mono",
                            xlim = c(420, 420),
                            hjust = "right",
                            # style segment
                            segment.curvature = .001,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            force_pull = 0.4,
                            force = 2,
                            size = 6,
                            fill = "white") 
# Create the plot
p.cum.plays <- ggplot(df, aes(x = day_of_year, y = cumulative_plays, color = as.factor(year))) +
  geom_line(size = 2)  +
  labs(title = "Total Plays",
       subtitle = "Running sum of tracks played in Spotify, by year",
       x = "Day in year",
       y = "Cumulative Plays") +
  theme_minimal() +
  scale_color_manual(values=as.vector(watlington(length(unique(df$year))))) +
  theme(text = element_text(size = 15),
        axis.title = element_text(size = 18),
        title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(1,3,0,0), "cm")) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label), 
                            family = "Spline Sans Mono",
                            xlim = c(420, 420),
                            hjust = "right",
                            # style segment
                            segment.curvature = .001,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            force_pull = 0.4,
                            force = 2,
                            size = 6,
                            fill = "white") 

# plot unique artists 

# Create the plot
p.cum.art <- ggplot(df, aes(x = day_of_year, y = unique_artists, color = as.factor(year))) +
  geom_line(size = 2)  +
  labs(title = "Total artists played",
       subtitle = "Running tally of how many unique artists\nover each year",
       x = "Day in the year",
       y = "Number of artists") +
  theme_minimal() +
  scale_color_manual(values=as.vector(watlington(length(unique(df$year))))) +
  theme(text = element_text(size = 15),
        axis.title = element_text(size = 18),
        title = element_text(size = 18, hjust = 0.5),
        legend.position = 'none',
        plot.margin = unit(c(1,3,0,0), "cm"),
        plot.subtitle = element_text(size = 16)) +
  coord_cartesian(clip = 'off') +
  ggrepel::geom_label_repel(aes(label = label), 
                            family = "Spline Sans Mono",
                            xlim = c(420, 420),
                            hjust = "right",
                            # style segment
                            segment.curvature = .001,
                            segment.inflect = TRUE, 
                            direction = 'y',
                            force_pull = 0.4,
                            force = 2,
                            size = 6,
                            fill = "white") 

wrap_plots(p.cum.plays, p.cum.time, ncol = 2) + plot_annotation(theme = theme(plot.title = element_text(size = 25, hjust = 0.5)))

```

```{r artist markers}
# Define Seasons
df$quarter <- case_when(
  lubridate::month(df$endTime) %in% c(1, 2, 3)  ~ 'Q1',
  lubridate::month(df$endTime) %in% c(4, 5, 6)  ~ 'Q2',
  lubridate::month(df$endTime) %in% c(7, 8, 9) ~ 'Q3',
  lubridate::month(df$endTime) %in% c(10, 11, 12) ~ 'Q4',
  TRUE ~ 'Unknown'
)

# Calculate the total and variance of listening time per artist per individual
artist_stats <- df %>%
  mutate(year_q = paste(year, quarter, sep = " - ")) %>% 
  group_by(year_q, artistName) %>%
  summarise(
    total_plays = sum(percent_listened),
    var_plays = var(percent_listened)
  ) %>%
  subset(total_plays >= 5)  # remove artists played less that 3 times

# Calculate the between-individual variance for each artist
between_var <- artist_stats %>%
  group_by(artistName) %>%
  summarise(between_var = var(total_plays)) 

# Join the within-individual and between-individual stats
artist_stats <- left_join(artist_stats, between_var, by = "artistName")


# Step 1: Identify the top 200 artists for each year
top_100_artists <- artist_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 200) %>%
  ungroup()

# Step 2: Identify artists that appear in the top 20 of more than one season
top_20_artists <- artist_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 20) %>%
  ungroup() %>%
  count(artistName) %>%
  filter(n > 3) 

# Step 2.5: Identify artists that appear in the top 5 of more than one group
top_5_artists <- artist_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 5) %>%
  ungroup() %>%
  count(artistName) %>%
  filter(n > 1) 

# Step 3: Identify artists that are unique after removing top 25 artists from any other year
unique_artists <- top_100_artists %>%
  anti_join(top_20_artists, by = "artistName") %>%
  anti_join(top_5_artists, by = "artistName")

# Step 4: Arrange by between-individual variance (if needed)
unique_top_artists <- unique_artists %>%
  group_by(year_q) |> 
  arrange(desc(between_var)) |> 
  slice_head(n = 50) |> 
  arrange(desc(total_plays)) |> 
  slice_head(n = 15) |> 
  select(year_q, artistName)

markers <- unique_top_artists %>%
  group_by(year_q) %>%
  mutate(marker_rank = row_number()) %>%
  ungroup() %>%
  filter(marker_rank <= 15) %>%  # Selecting top 10 unique markers for each individual
  select(year_q, marker_rank, artistName) %>%
  pivot_wider(names_from = year_q, values_from = artistName) %>%
  arrange(marker_rank)


colnames(markers)[1] <- c("Marker Rank")

write.csv(markers, paste0("~/results/individuals/", id, "/yr_seas_art_markers.csv"), row.names = F)
```
```{r track markers}

# Calculate the total and variance of listening time per track per individual
track_stats <- df %>%
  mutate(year_q = paste(year, quarter, sep = " - ")) %>% 
  group_by(year_q, trackName) %>%
  summarise(
    total_plays = sum(percent_listened),
    var_plays = var(percent_listened)
  ) %>%
  subset(total_plays >= 3)  # remove tracks played less that 3 times

# Calculate the between-individual variance for each track
between_var <- track_stats %>%
  group_by(trackName) %>%
  summarise(between_var = var(total_plays)) 

# Join the within-individual and between-individual stats
track_stats <- left_join(track_stats, between_var, by = "trackName")


# Step 1: Identify the top 50 tracks for each year
top_100_tracks <- track_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 100) %>%
  ungroup()

# Step 2: Identify tracks that appear in the top 20 of more than one season
top_20_tracks <- track_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 20) %>%
  ungroup() %>%
  group_by(trackName) %>%
  tally() %>%
  filter(n > 5)

# Step 2.5: Identify tracks that appear in the top 5 of more than one group
top_5_tracks <- track_stats %>%
  group_by(year_q) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 5) %>%
  ungroup() %>%
  group_by(trackName) %>%
  tally() %>%
  filter(n > 1)

# Step 3: Identify tracks that are unique after removing top 25 tracks from any other year
unique_tracks <- top_100_tracks %>%
  anti_join(top_20_tracks, by = "trackName") %>%
  anti_join(top_5_tracks, by = "trackName")

# Step 4: Arrange by between-individual variance (if needed)
unique_top_tracks <- unique_tracks %>%
  group_by(year_q) |> 
  arrange(desc(between_var)) |> 
  slice_head(n = 50) |> 
  arrange(desc(total_plays)) |> 
  slice_head(n = 15) |> 
  select(year_q, trackName)

markers <- unique_top_tracks %>%
  group_by(year_q) %>%
  mutate(marker_rank = row_number()) %>%
  ungroup() %>%
  filter(marker_rank <= 15) %>%  # Selecting top 10 unique markers for each individual
  select(year_q, marker_rank, trackName) %>%
  pivot_wider(names_from = year_q, values_from = trackName) %>%
  arrange(marker_rank)


colnames(markers)[1] <- c("Marker Rank")

write.csv(markers, paste0("~/results/individuals/", id, "/yr_seas_art_markers.csv"), row.names = F)
```

```{r track markers}

# Calculate the total and variance of listening time per track per individual
track_stats <- df %>%
  #mutate(year_q = paste(year, quarter, sep = " - ")) %>% 
  group_by(year, trackName) %>%
  summarise(
    total_plays = sum(percent_listened),
    var_plays = var(percent_listened)
  ) %>%
  subset(total_plays >= 3)  # remove tracks played less that 3 times

# Calculate the between-individual variance for each track
between_var <- track_stats %>%
  group_by(trackName) %>%
  summarise(between_var = var(total_plays)) 

# Join the within-individual and between-individual stats
track_stats <- left_join(track_stats, between_var, by = "trackName")


# Step 1: Identify the top 50 tracks for each year
top_100_tracks <- track_stats %>%
  group_by(year) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 200) %>%
  ungroup()

# Step 2: Identify tracks that appear in the top 20 of more than one season
top_20_tracks <- track_stats %>%
  group_by(year) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 30) %>%
  ungroup() %>%
  group_by(trackName) %>%
  tally() %>%
  filter(n > 3)

# Step 2.5: Identify tracks that appear in the top 5 of more than one group
top_5_tracks <- track_stats %>%
  group_by(year) %>%
  arrange(desc(total_plays)) %>%
  slice_head(n = 5) %>%
  ungroup() %>%
  group_by(trackName) %>%
  tally() %>%
  filter(n > 1)

# Step 3: Identify tracks that are unique after removing top 25 tracks from any other year
unique_tracks <- top_100_tracks %>%
  anti_join(top_20_tracks, by = "trackName") %>%
  anti_join(top_5_tracks, by = "trackName")

# Step 4: Arrange by between-individual variance (if needed)
unique_top_tracks <- unique_tracks %>%
  group_by(year) |> 
  arrange(desc(between_var)) |> 
  slice_head(n = 50) |> 
  arrange(desc(total_plays)) |> 
  slice_head(n = 15) |> 
  select(year, trackName)

markers <- unique_top_tracks %>%
  group_by(year) %>%
  mutate(marker_rank = row_number()) %>%
  ungroup() %>%
  filter(marker_rank <= 15) %>%  # Selecting top 10 unique markers for each individual
  select(year, marker_rank, trackName) %>%
  pivot_wider(names_from = year, values_from = trackName) %>%
  arrange(marker_rank)


colnames(markers)[1] <- c("Marker Rank")

write.csv(markers, paste0("~/results/individuals/", id, "/yr_track_markers.csv"), row.names = F)
```