---
title: "Cluster by song attributes"
author: "Brian Gural"
date: "2023-09-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libs}
# Load necessary libraries
libs <- c("tidyverse")
lapply(libs, require, character.only = T)
```

```{r load data}
# Load listening data and match naming to attributes data
lis.df <- read.csv("data/raw/listen_history_1year.csv", row.names = 1)
colnames(lis.df)[2:3] <- c("artist_name", "track_name")

# Load attributes data for personal top 100 artists of the past year
att.df <- read.csv("data/attributes/batched_slurm/art_ft_1_100.csv") 

att.df.101 <- read.csv("data/attributes/batched_slurm/art_ft_101_500.csv") 

att.df <- rbind(att.df, att.df.101)

write.csv(att.df, "data/attributes/batched_slurm/art_ft_1_500.csv") 
# Check overlap of tracks in listening data and in attributes data
table(lis.df$track_name %in% att.df$track_name)
```

```{r subset to top}
# Remove trailing white spaces
lis.ws <- sapply(lis.df, function(x){trimws(x, "both")}) |> as.data.frame()
att.ws <- sapply(att.df, function(x){trimws(x, "both")}) |> as.data.frame()

# Make column for minutes played, total by track. Then join with attributes data
lis.t <- lis.ws |>
         group_by(track_name) |>
         summarise(min_played = sum(as.numeric(msPlayed)/(1000*60))) |> 
         arrange(desc(min_played)) %>%
         inner_join(distinct(att.ws), by = "track_name") 

```

```{r save joined}

write.csv(lis.t, "data/merged_datasets/bg_1y_t500.csv", row.names = F)

```
